/*
 * Copyright (C) 2026 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class TurbineStartStartDialog extends javax.swing.JDialog {
    
    /**
     * Creates new form HowtoStartDialog
     */
    public TurbineStartStartDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("How to start");
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("The turbine warmup procedure for cold start is designed to have the turbine spin up and synced to grid without the steam reheater, warming the high pressure part first. The steam drums pressure setpoint used for startup is defined as a function of thermal reactor output and can be viewed with a diagram representing it.\n\nThose are the designed turbine hold points with steam parameters and reactor power and the neutron flux setpoints.\n\n0750 1/min - 15 bar - 140 MWth - 4.7 %N\n1500 1/min - 27 bar - 206 MWth - 7.0 %N\n2250 1/min - 38 bar - 263 MWth - 8.8 %N\n3000 1/min - 50 bar - 326 MWth - 10.9 %N\n\nIt is not neccessary to have precisely those values.\n\nThe turbine should be synced to grid with 50 bars. From a neutron setpoint of 13 %N, the pressure setpoint will be 64 bars.\n\nWith 15 %N, start heating up the low pressure turbine by carefully using the steam reheater.\n");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
